import Head from 'next/head'
import Image from 'next/image'
import WeatherForm from '../components/currentWeather';
import FiveDayForecast from '../components/fiveDayForecast';

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            zIndex: -1,
            position: "fixed",
            width: "100vw",
            height: "100vh",
          }}
        >
          <Image
            src="/clouds.jpg"
            alt="clouds img"
            style={{
              objectFit: "cover",
            }}
            fill
          />
        </div>
        <div
          style={{
            paddingTop: "30px",
          }}
        >
          <WeatherForm />
          <FiveDayForecast />
        </div>
      </main>
    </>
  );
}
